language: c
matrix:
  include:
    - name: linux x86_64 and i686 / mingw x64 and x32 on Wine
      os: linux
      sudo: required
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-multilib
            - mingw-w64
            - wine64
            - wine32
            - wine-binfmt
      before_script:
        - sudo update-binfmts --import wine
      script:
        - ./.travis/run-cmake-test.sh x86_64-linux
        - ./.travis/run-cmake-test.sh i686-linux     -DCMAKE_C_FLAGS=-m32 -DCMAKE_ASM_FLAGS=-m32
        - ./.travis/run-cmake-test.sh x86_64-mingw32 -DCMAKE_TOOLCHAIN_FILE=../cmake/x86_64-w64-mingw32.cmake
        - ./.travis/run-cmake-test.sh i686-mingw32   -DCMAKE_TOOLCHAIN_FILE=../cmake/i686-w64-mingw32.cmake
    - name: alpine linux on docker
      os: linux
      dist: bionic
      before_script:
        - docker build -f .travis/Dockerfile-alpine-test -t funchook-test .
      script:
        - docker run --rm funchook-test
    - name: Xcode 11.3 (the latest version)
      os: osx
      osx_image: xcode11.3
      script:
        - ./.travis/run-cmake-test.sh x86_64-darwin
    - name: Xcode 10.3 (the latest version which can change memory regions in exe)
      os: osx
      osx_image: xcode10.3
      script:
        - ./.travis/run-cmake-test.sh x86_64-darwin
    - name: Xcode 10.1 (the latest version supporting 32-bit)
      os: osx
      osx_image: xcode10.1
      script:
        - ./.travis/run-cmake-test.sh x86_64-darwin
        - ./.travis/run-cmake-test.sh i686-darwin -DCMAKE_C_FLAGS=-m32 -DCMAKE_ASM_FLAGS=-m32
    - name: Windows
      os: windows
      script:
        - ./.travis/run-cmake-test.sh x86_64-windows -G "Visual Studio 15 2017 Win64"
        - ./.travis/run-cmake-test.sh x86-windows -G "Visual Studio 15 2017"
